# Site settings
title: CodeSweetness
email: annagaiel@gmail.com
description: A blog about what I'm learning.
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: annanatorilla
gems: [jekyll-paginate, jekyll-gist]
paginate: 5

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Anna Natorilla
      layout: "post"
      category: conferences
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
